---
title: "DS_HW_2"
author: "Conor Gillingham and Macey Jacobs"
date: "2024-10-01"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T,
                      results = "hide")
```
# Question 1
```{r}
library(tidyverse)
tribble( ~x, ~y, ~w, ~z,
         210, 300, 220, 180,
         102, 100, 119, 187,
         176, 175, 188, 173,
         87, 95, 91, 94,
         202, 210, 234, 218,
         110, 122, 131, 128,
) -> dt
dt
```
## 1a
```{r}
map_dbl(dt, mean)
```
## 1b
```{r}
map_dbl(dt, sd)
```
## 1c
```{r}
map(dt, sqrt)
```
## 1d
```{r}
summary(dt)
```
# Question 2
## 2a
```{r}
#part 2 setup
df <- c()
for (val in 1:10000){
  rexp(5) -> 
  new_val
  meanval <- mean(new_val)
  df <- append(df,new_val)
  }
head(df)
hist(df)
```
## 2b
```{r}
nf <- c()
map_dbl(1:10000, ~mean(rexp(5,)))
```
## 2c
```{r}
nf <- replicate(10000, mean(rexp(5,)))
nf
```
# Question 3
```{r}
val <- c(5, 10, 20)
for (item in val){
  nf <- replicate(10000, mean(rexp(item,)))
  hist(nf,
       main = item)
}
```